import type {NextPage} from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="flex justify-center items-center mt-6">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div className="bg-white shadow-lg w-52 h-96 p-6 rounded-3xl">
        hello
      </div>
    </div>
  )
}

export default Home
