import {CoinResponse} from "../dto/CoinResponse";

export const mockCoinResponses: readonly CoinResponse[] = [{
  "id": "btc-bitcoin",
  "name": "Bitcoin",
  "symbol": "BTC",
  "rank": 1,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "eth-ethereum",
  "name": "Ethereum",
  "symbol": "ETH",
  "rank": 2,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "usdt-tether",
  "name": "Tether",
  "symbol": "USDT",
  "rank": 3,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "bnb-binance-coin",
  "name": "Binance Coin",
  "symbol": "BNB",
  "rank": 4,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "sol-solana",
  "name": "Solana",
  "symbol": "SOL",
  "rank": 5,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "steth-lido-staked-ether",
  "name": "Lido Staked Ether",
  "symbol": "STETH",
  "rank": 6,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "xrp-xrp",
  "name": "XRP",
  "symbol": "XRP",
  "rank": 7,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "usdc-usd-coin",
  "name": "USDC",
  "symbol": "USDC",
  "rank": 8,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "ada-cardano",
  "name": "Cardano",
  "symbol": "ADA",
  "rank": 9,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "doge-dogecoin",
  "name": "Dogecoin",
  "symbol": "DOGE",
  "rank": 10,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "shib-shiba-inu",
  "name": "Shiba Inu",
  "symbol": "SHIB",
  "rank": 11,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "avax-avalanche",
  "name": "Avalanche",
  "symbol": "AVAX",
  "rank": 12,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "weth-weth",
  "name": "WETH",
  "symbol": "WETH",
  "rank": 13,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "dot-polkadot",
  "name": "Polkadot",
  "symbol": "DOT",
  "rank": 14,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "trx-tron",
  "name": "TRON",
  "symbol": "TRX",
  "rank": 15,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "link-chainlink",
  "name": "Chainlink",
  "symbol": "LINK",
  "rank": 16,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "matic-polygon",
  "name": "Polygon",
  "symbol": "MATIC",
  "rank": 17,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "wbtc-wrapped-bitcoin",
  "name": "Wrapped Bitcoin",
  "symbol": "WBTC",
  "rank": 18,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "uni-uniswap",
  "name": "Uniswap",
  "symbol": "UNI",
  "rank": 19,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "bch-bitcoin-cash",
  "name": "Bitcoin Cash",
  "symbol": "BCH",
  "rank": 20,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "icp-internet-computer",
  "name": "Internet Computer",
  "symbol": "ICP",
  "rank": 21,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "ltc-litecoin",
  "name": "Litecoin",
  "symbol": "LTC",
  "rank": 22,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "etc-ethereum-classic",
  "name": "Ethereum Classic",
  "symbol": "ETC",
  "rank": 23,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "near-near-protocol",
  "name": "Near Protocol",
  "symbol": "NEAR",
  "rank": 24,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "leo-leo-token",
  "name": "LEO Token",
  "symbol": "LEO",
  "rank": 25,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "fil-filecoin",
  "name": "Filecoin",
  "symbol": "FIL",
  "rank": 26,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "atom-cosmos",
  "name": "Cosmos",
  "symbol": "ATOM",
  "rank": 27,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "btcb-binance-bitcoin",
  "name": "Binance Bitcoin",
  "symbol": "BTCB",
  "rank": 28,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "apt-aptos",
  "name": "Aptos",
  "symbol": "APT",
  "rank": 29,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "tao-bittensor",
  "name": "BitTensor",
  "symbol": "TAO",
  "rank": 30,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "op-optimism",
  "name": "Optimism",
  "symbol": "OP",
  "rank": 31,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "imx-immutable-x",
  "name": "Immutable X",
  "symbol": "IMX",
  "rank": 32,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "dai-dai",
  "name": "Dai",
  "symbol": "DAI",
  "rank": 33,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "hbar-hedera-hashgraph",
  "name": "Hedera Hashgraph",
  "symbol": "HBAR",
  "rank": 34,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "cro-cryptocom-chain",
  "name": "Cronos",
  "symbol": "CRO",
  "rank": 35,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "stx-stacks",
  "name": "Stacks",
  "symbol": "STX",
  "rank": 36,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "toncoin-the-open-network",
  "name": "Toncoin",
  "symbol": "TON",
  "rank": 37,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "xlm-stellar",
  "name": "Stellar",
  "symbol": "XLM",
  "rank": 38,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "inj-injective-protocol",
  "name": "Injective Protocol",
  "symbol": "INJ",
  "rank": 39,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "rndr-render-token",
  "name": "Render Token",
  "symbol": "RNDR",
  "rank": 40,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "pepe-pepe",
  "name": "Pepe",
  "symbol": "PEPE",
  "rank": 41,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "okb-okb",
  "name": "OKB",
  "symbol": "OKB",
  "rank": 42,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "kas-kaspa",
  "name": "Kaspa",
  "symbol": "KAS",
  "rank": 43,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "vet-vechain",
  "name": "VeChain",
  "symbol": "VET",
  "rank": 44,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "mnt-mantle",
  "name": "Mantle",
  "symbol": "MNT",
  "rank": 45,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "fdusd-first-digital-usd",
  "name": "First Digital USD",
  "symbol": "FDUSD",
  "rank": 46,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "grt-the-graph",
  "name": "The Graph",
  "symbol": "GRT",
  "rank": 47,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "theta-theta-token",
  "name": "THETA",
  "symbol": "THETA",
  "rank": 48,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "ldo-lido-dao",
  "name": "Lido DAO",
  "symbol": "LDO",
  "rank": 49,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "arb-arbitrum",
  "name": "Arbitrum",
  "symbol": "ARB",
  "rank": 50,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "xmr-monero",
  "name": "Monero",
  "symbol": "XMR",
  "rank": 51,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "tia-celestia",
  "name": "Celestia",
  "symbol": "TIA",
  "rank": 52,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "pls-pulsechain",
  "name": "Pulsechain",
  "symbol": "PLS",
  "rank": 53,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "rune-thorchain",
  "name": "THORChain",
  "symbol": "RUNE",
  "rank": 54,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "ar-arweave",
  "name": "Arweave",
  "symbol": "AR",
  "rank": 55,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "reth-rocket-pool-eth",
  "name": "Rocket Pool ETH",
  "symbol": "RETH",
  "rank": 56,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "ftm-fantom",
  "name": "Fantom",
  "symbol": "FTM",
  "rank": 57,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "bsv-bitcoin-sv",
  "name": "Bitcoin SV",
  "symbol": "BSV",
  "rank": 58,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "algo-algorand",
  "name": "Algorand",
  "symbol": "ALGO",
  "rank": 59,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "fetch-ai",
  "name": "Fetch.AI",
  "symbol": "FET",
  "rank": 60,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "bonk-bonk",
  "name": "Bonk",
  "symbol": "BONK",
  "rank": 61,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "wif-dogwifcoin",
  "name": "dogwifcoin",
  "symbol": "WIF",
  "rank": 62,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "floki-floki-inu",
  "name": "Floki Inu",
  "symbol": "FLOKI",
  "rank": 63,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "beam-beam-eth",
  "name": "Beam Token",
  "symbol": "BEAM",
  "rank": 64,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "aave-new",
  "name": "Aave",
  "symbol": "AAVE",
  "rank": 65,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "mkr-maker",
  "name": "Maker",
  "symbol": "MKR",
  "rank": 66,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "sui-sui",
  "name": "Sui",
  "symbol": "SUI",
  "rank": 67,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "hex-hex-from-pulsechain",
  "name": "HEX from Pulsechain",
  "symbol": "HEX",
  "rank": 68,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "egld-elrond",
  "name": "MultiversX (Elrond)",
  "symbol": "EGLD",
  "rank": 69,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "bttc-bittorrent-chain",
  "name": "BitTorrent",
  "symbol": "BTT",
  "rank": 70,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "strk-starknet",
  "name": "Starknet",
  "symbol": "STRK",
  "rank": 71,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "plsx-pulsex",
  "name": "PulseX",
  "symbol": "PLSX",
  "rank": 72,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "ordi-ordinals",
  "name": "Ordinals",
  "symbol": "ORDI",
  "rank": 73,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "sei-sei",
  "name": "Sei",
  "symbol": "SEI",
  "rank": 74,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "sand-the-sandbox",
  "name": "The Sandbox",
  "symbol": "SAND",
  "rank": 75,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "rbn-ribbon-finance",
  "name": "Ribbon Finance",
  "symbol": "RBN",
  "rank": 76,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "qnt-quant",
  "name": "Quant",
  "symbol": "QNT",
  "rank": 77,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "axs-axie-infinity",
  "name": "Axie Infinity",
  "symbol": "AXS",
  "rank": 78,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "agix-singularitynet",
  "name": "Singularity NET",
  "symbol": "AGIX",
  "rank": 79,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "kcs-kucoin-token",
  "name": "KuCoin Token",
  "symbol": "KCS",
  "rank": 80,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "flr-flare-network",
  "name": "Flare Network",
  "symbol": "FLR",
  "rank": 81,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "hnt-helium",
  "name": "Helium",
  "symbol": "HNT",
  "rank": 82,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "akt-akash-network",
  "name": "Akash Network",
  "symbol": "AKT",
  "rank": 83,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "xtz-tezos",
  "name": "Tezos",
  "symbol": "XTZ",
  "rank": 84,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "mina-mina-protocol",
  "name": "Mina Protocol",
  "symbol": "MINA",
  "rank": 85,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "chz-chiliz",
  "name": "Chiliz",
  "symbol": "CHZ",
  "rank": 86,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "flow-flow",
  "name": "Flow",
  "symbol": "FLOW",
  "rank": 87,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "snx-synthetix-network-token",
  "name": "Synthetix Network Token",
  "symbol": "SNX",
  "rank": 88,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "xec-ecash",
  "name": "eCash",
  "symbol": "XEC",
  "rank": 89,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "luna-terra",
  "name": "Terra Classic",
  "symbol": "LUNC",
  "rank": 90,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "ape-apecoin",
  "name": "ApeCoin",
  "symbol": "APE",
  "rank": 91,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "tusd-trueusd",
  "name": "TrueUSD",
  "symbol": "TUSD",
  "rank": 92,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "wpls-wrapped-pulse",
  "name": "Wrapped Pulse",
  "symbol": "WPLS",
  "rank": 93,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "mana-decentraland",
  "name": "Decentraland",
  "symbol": "MANA",
  "rank": 94,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "ico-axelar",
  "name": "Axelar",
  "symbol": "AXL",
  "rank": 95,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "gala-gala",
  "name": "Gala",
  "symbol": "GALA",
  "rank": 96,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "bgb-bitget-token",
  "name": "Bitget Token",
  "symbol": "BGB",
  "rank": 97,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "cfx-conflux-network",
  "name": "Conflux Network",
  "symbol": "CFX",
  "rank": 98,
  "is_new": false,
  "is_active": true,
  "type": "token"
}, {
  "id": "wbt-whitebit",
  "name": "WhiteBIT Coin",
  "symbol": "WBT",
  "rank": 99,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}, {
  "id": "neo-neo",
  "name": "NEO",
  "symbol": "NEO",
  "rank": 100,
  "is_new": false,
  "is_active": true,
  "type": "coin"
}];