import type { Metadata } from "next";
import {Patrick_Hand} from "next/font/google"
import "@/styles/globals.css";

const patrickHand = Patrick_Hand({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-patrick-hand"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={patrickHand.style}>{children}</body>
    </html>
  );
}
